---
abstract: 'generate random newspaper headlines'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Daily-Fail
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Acme::Daily::Fail:
    file: lib/Acme/Daily/Fail.pm
    version: 1.04
requires:
  Math::Random: 0.69
  constant: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/acme-daily-fail/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/acme-daily-fail.git
version: 1.04
