---
abstract: 'generate random newspaper headlines'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Daily-Fail
requires:
  Math::Random: '0.69'
  constant: '0'
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/acme-daily-fail
  repository: https://github.com/bingos/acme-daily-fail.git
version: '1.08'
